---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Service
metadata:
  name: service-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    type: sample
    description: Sample Service
    enabled: true