---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Group
metadata:
  name: group-sample
spec:
  cloudCredentialsRef:
    # TODO(scaffolding): Use openstack-admin if the resouce needs admin credentials to be created
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Group
    # TODO(scaffolding): Add all fields the resource supports
