---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: ShareType
metadata:
  name: sharetype-sample
spec:
  cloudCredentialsRef:
    # TODO(scaffolding): Use openstack-admin if the resource needs admin credentials to be created
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample ShareType
    # TODO(scaffolding): Add all fields the resource supports
