---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: AddressScope
metadata:
  name: addressscope-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    ipVersion: 4
