---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: ApplicationCredential
metadata:
  name: applicationcredential-sample
spec:
  cloudCredentialsRef:
    # TODO(scaffolding): Use openstack-admin if the resource needs admin credentials to be created
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample ApplicationCredential
    # TODO(scaffolding): Add all fields the resource supports
