apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Server
metadata:
  name: server-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    imageRef: server-sample
    flavorRef: server-sample
    ports:
      - portRef: server-sample
    volumes:
      - volumeRef: server-sample
    serverGroupRef: server-sample
    keypairRef: server-sample
    availabilityZone: nova
    tags:
      - tag1
      - tag2
