apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Domain
metadata:
  name: role-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource: {}
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Role
metadata:
  name: role-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Role
    domainRef: role-sample