apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Domain
metadata:
  name: group-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource: {}
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Group
metadata:
  name: group-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Group
    domainRef: group-sample
