---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: User
metadata:
  name: user-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample User
