---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: ApplicationCredential
metadata:
  name: applicationcredential-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample ApplicationCredential
    name: application-credential
    userID: "00000000000000000000000000000000"
    unrestricted: False
    secret: "Secret"
    roles:
      - name: "role-name"
    accessRules:
      - method: "GET"
        service: "monitoring"
    expiresAt: "2022-02-02T22:22:22.000000"
