name: release image

on:
  push:
    tags:
      - v**

permissions:
  contents: read

env:
  image_tag: quay.io/orc/openstack-resource-controller:${GITHUB_REF_NAME}
  bundle_image_tag: quay.io/orc/openstack-resource-controller-bundle:${GITHUB_REF_NAME}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
      with:
        # Required for git describe to generate correct output for populating
        # build variables
        fetch-depth: 0
        fetch-tags: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Install build dependencies
      run: sudo apt-get install -y libgpgme-dev

    - run: |
        docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_TOKEN }}" quay.io
        make docker-buildx IMG=${{ env.image_tag }}
        make build-bundle-image BUNDLE_IMG=${{ env.bundle_image_tag }}
        make docker-push IMG=${{ env.bundle_image_tag }}
