name: Weekly security scan

on:
  schedule:
  # Cron for every Monday at 8:42 UTC.
  - cron: "42 8 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        branch: [main, release-1.0]
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v4.2.2
      with:
        ref: ${{ matrix.branch }}
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # tag=v6.2.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run verify security target
      run: make verify-security
